---
- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - unzip
    - php5-cli
    - php5-fpm
    - php5-mysql
    - php5-imap
    - php5-curl
    - php5-gd

- name: Find PHP ini file
  shell: find /etc -name php.ini | fgrep fpm
  register: suitecrm_php_ini_file

- name: Configure PHP timezone
  replace: dest={{ suitecrm_php_ini_file.stdout }} regexp='^;date.timezone =$' replace='date.timezone = {{ suitecrm_timezone }}' backup=yes
  notify:
  - restart php-fpm
  - restart nginx

- name: Configure PHP file upload_max_filesize
  replace: dest={{ suitecrm_php_ini_file.stdout }} regexp='^upload_max_filesize = .*$' replace='upload_max_filesize = 30M' backup=yes
  notify:
  - restart php-fpm
  - restart nginx

- name: Configure PHP max_execution_time
  replace: dest={{ suitecrm_php_ini_file.stdout }} regexp='^max_execution_time = .*$' replace='max_execution_time = 300' backup=yes
  notify:
  - restart php-fpm
  - restart nginx

- name: Configure PHP memory_limit
  replace: dest={{ suitecrm_php_ini_file.stdout }} regexp='^memory_limit = .*$' replace='memory_limit = 512M' backup=yes
  notify:
  - restart php-fpm
  - restart nginx

- name: Configure PHP post_max_size
  replace: dest={{ suitecrm_php_ini_file.stdout }} regexp='^post_max_size = .*$' replace='post_max_size = 30M' backup=yes
  notify:
  - restart php-fpm
  - restart nginx

- name: Configure PHP-fpm request_terminate_timeout
  lineinfile: dest=/etc/php5/fpm/php-fpm.conf line="request_terminate_timeout = 300"
  notify:
  - restart php-fpm
  - restart nginx

- name: Enable PHP IMPA module
  shell: php5enmod imap
  notify:
  - restart php-fpm
  - restart nginx

- name: Create installation directory
  file: path={{ suitecrm_install_dir }} state=directory

- name: Copy SuiteCRM zipfile
  copy: src='SuiteCRM-{{ suitecrm_version }} MAX.zip' dest={{ suitecrm_install_dir }}

# Doesn't really create "{{ suitecrm_install_dir }}/suitecrm", but we want to not do all this work if that symlink already exists
# Would be nice if ansible could handle multiple files in the creates arg :(
- name: Unzip SuiteCRM
  command: unzip -o 'SuiteCRM-{{ suitecrm_version }} MAX.zip'
  args:
    chdir: "{{ suitecrm_install_dir }}"
    creates: "{{ suitecrm_install_dir }}/suitecrm"

- name: Create versionless symlink
  file: src={{ suitecrm_install_dir }}/suitecrm-{{ suitecrm_version }}-max dest={{ suitecrm_install_dir }}/suitecrm state=link

- name: Set up crontab
  cron: name="suitecrm scheduler" job="su -s /bin/bash -c 'cd /var/www/suitecrm; php -f cron.php > /dev/null 2>&1' www-data"
